import smtplib #used to send SMTP emails
from socket import gaierror #used for error handling
import string
import random

#following code defines the SMTP credentials
##port = 2525 
##smtp_server = "smtp.mailtrap.io"
##login = "1a2b3c4d5e6f7g" # paste your login generated by Mailtrap
##password = "1a2b3c4d5e6f7g" # paste your password generated by Mailtrap

#The following code defines the sender and receiver
sender = "from@example.com"
receiver = "mailtrap@example.com"

#The following code comes up with a random code and a message to be sent
code=""
for i in range(6):
    code = code+random.choice(string.ascii_letters)
    code = code+str(random.randint(0,10))

message = f"""\
Subject: Spelling Test Authentication Code
To: {receiver}
From: {sender}
Your code is {code}."""

#the following code sends the email and does error detection
##try:
##    #send your message with credentials specified above
##    with smtplib.SMTP(smtp_server, port) as server:
##        server.login(login, password)
##        server.sendmail(sender, receiver, message)
##
##    # tell the script to report if your message was sent or which errors need to be fixed 
##    print('Sent')
##except (gaierror, ConnectionRefusedError):
##    print('Failed to connect to the server. Bad connection settings?')
##except smtplib.SMTPServerDisconnected:
##    print('Failed to connect to the server. Wrong user/password?')
##except smtplib.SMTPException as e:
##    print('SMTP error occurred: ' + str(e))

print(code)
